spring:
  application:
    name: back
  datasource:
    url: jdbc:mysql://localhost:3306/gestao?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/oauth2/authorize
          jwk-set-uri: http://localhost:8080/oauth2/jwks
      authorization:
        server:
          client-registration-uri: /oauth2/register
          authorization-consent-uri: /oauth2/consent
          authorization-endpoint:
            uri: /oauth2/authorize
          token-endpoint:
            uri: /oauth2/token
          jwk-set-uri: /oauth2/jwks

server:
  port: 8080

jwt:
  secret: uG29MbXRgK6Vzp02VzJdF3RNb7Ny6ZH9nWZS4d6LPCvXmwt0vGb36WvZmTx4EL7aCWx7B8N5xQjamY3JqdKLT7zpSv88DtNS24pH
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 2592000
  refresh-token-max-age: 30d
  cookie:
    refresh-token: refreshToken
    access-token: accessToken
    secure: true
    http-only: true
    same-site: strict 
